### ISSUE TITLE
Instructions for citing Predicer?

### ISSUE THREAD

**Issue by Tasqu** [vttresearch/Predicer#9]
@sundelld currently, there don't seem to be any instructions for citing Predicer?

I'd recommend creating a VTT pure entry for it, which could be used for the time being. Later, we might want to switch citing to a publication or create a Zenodo repository with a DOI through GitHub-Zenodo integration, if I can get the admins of vttresearch to enable it.

For now, I'll use the following citation _(based on what PURE formatting will most likely look like)_:
>Sundell, D.; Pursiheimo, E. (2022). Predicer: Predictive decider for actors making decisions over multiple stages. Software, VTT Technical Research Centre of Finland. https://github.com/vttresearch/Predicer

**Comment by tkorvola** [comment]
README.md now has a link to the Optimization and Engineering paper. Close?
